[package]
name = "reset"
authors = ["tpmccallum <tim.mccallum@fermyon.com>"]
description = "A path that lets you reset whether your node is too busy to take on tasks"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"

[workspace]
